### ISSUE TITLE
DB backups

### ISSUE THREAD

**Issue by profy12** [O-clock-Dev/teleporter-compose#18]
:fr: 
Les bases de données doivent pourvoir être sauvegardées, il faut trouver un mécanisme de backup/restauration.

Les backups doivent être stockés dans un mount bind sur le poste apprenant, avec une rétention d'une semaine.

Pourquoi pas un stockage cloud par la suite.

### Edit@Translation:
:gb: 

Databases must be able to be backed up, and a backup/restore mechanism must be found.

Backups should be stored in a mount bind on the learner workstation, with a retention period of one week.

Why not store them in the cloud afterwards?

**Comment by clementgoclock** [comment]
We currently host 3 DMBS:
* MariaDB
* PostgreSQL
* MongoDB

The first solution is to add and host single volumes, one for each system.
Another solution could be to use a single volume and backup only that one. This could simplify the backup solution. However, it's important to note that when multiple containers access the same volume on a host, file locks must be managed by the applications running in the containers, otherwise there may be risks.

Exemple for a single, shared, volume: 
```
services:
  db_mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  db_postgres:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db_data:
```

[Documentation](https://docs.docker.com/storage/volumes/#back-up-restore-or-migrate-data-volumes) for backing up data volumes

Another solution could be to use remote volume hosting (such as Amazon EBS) or to enhance volume management with [volume plugins](https://docs.docker.com/engine/extend/plugins_volume/), some [examples](https://docs.docker.com/engine/extend/legacy_plugins/).

Just to recall something: data volumes can be initiated with backup through `--volumes-from` option.

Another another solution could be to use the [container backup](https://docs.docker.com/desktop/backup-and-restore/).

Just letting everything sink in before chosing solution.
