### ISSUE TITLE
Rendre vpn.env optionnel au lancement

### ISSUE THREAD

**Issue by clementgineste** [O-clock-Dev/teleporter-compose#27]
Actuellement `vpn.env` est nécéssaire pour lancer le TP, il y est - vide - dans la code base pour permettre le lancement sans encombre au premier `git clone` 

Cependant pour travailler c'est désagréable, il faut bien veiller à ne pas pousser son `vpn.env` quand on commit. Il faut aussi faire un copy sur un fichier déjà présent, etc.

Il faudrait que le `vpn.env` ne soit pas obligatoire pour lancer le compose.

Solution initiale : https://docs.docker.com/compose/environment-variables/set-environment-variables/
```
env_file:
  - path: ./default.env
    required: true # default
  - path: ./override.env
    required: false
```
Sensé marche dans la définition d'un service mais au niveau du compose (via l'include) docker compose explose (yep il pète, même pas un error ou warning, il pète).
A voir si c'est un bug ou une feature.
